version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "${PORT:-3000}:80"
    env_file:
      - .env
    networks:
      - todo-frontend-network

networks:
  todo-frontend-network:
    driver: bridge